/*
開發者-列表
*/

CREATE TABLE IF NOT EXISTS developer_list (
  ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  LocalIP VARCHAR(15) DEFAULT '',
  AgentID VARCHAR(36) NOT NULL,
  UName VARCHAR(20) NOT NULL,
  Money DECIMAL(20, 4)
);