/*
使用者-列表

TheirGrant {0:正式, 1:非 0 都為測試}
*/
CREATE TABLE IF NOT EXISTS user_list (
  ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  LastIP VARCHAR(15) DEFAULT '',
  AgentID VARCHAR(36) NOT NULL,
  TheirUID VARCHAR(36) NOT NULL,
  TheirUName VARCHAR(20) NOT NULL,
  TheirUGrant VARCHAR(2) DEFAULT '1',
  CreatedAt DATETIME NOT NULL,
  ModifiedAt DATETIME NOT NULL
);